services:
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/opc/emfcamp/caddy/data:/data
      - /home/opc/emfcamp/caddy/config:/config
      - /home/opc/emfcamp/caddy/Caddyfile:/etc/caddy/Caddyfile
  babbling-clock:
    image: mendhak/http-https-echo:24
    container_name: babbling-clock
    hostname: babbling-clock
  schedule-ics:
    build:
      context: ./schedule-to-ics
